import "./globals.css";
import Header from "./Components/Header";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header user={"Rohit"} editor={"editor sahab"}/>
        {children}
      </body>
    </html>
  );
}
